### PR TITLE
Add orderbook level 2 aggregation

### PR DESCRIPTION
**Pull request by fdocr**
So this project I'm working on would benefit from having a [level 2 orderbook](https://docs.gdax.com/#the-code-classprettyprintlevel2code-channel). Not sure if this would be useful for the general project, or maybe you have some pointers on implementation/alternatives... But here's the PR either way :)

### CODE REVIEW

**Comment by mikerodrigues** [comment]
Thanks for another PR. I think this would be a great addition to the project. I would change a few things.

A Level 2 orderbook aggregates the top 50, but your methods aggregate all of them. It would probably be cool to have the methods support an optional argument like "top_n" so it's configurable.

I'd also change the names, since it's technically not a "Level 2" orderbook if it's not top 50. I'm kind of a stickler for method name consistency. I'd go with:

`aggregate(top_n)`
`aggregate_bids(top_n)`
`aggregate_asks(top_n)`

The hashes returned should probably also include a `:num_orders` key like the API.

I'm interested in hearing more about your project if you're willing to share.

**Comment by fdocr** [comment]
Hi again, you're very welcome and thank you for the project to begin with (also your contributions to the base coinbase-exchange gem).

I just committed/squashed an updated version based on your comments and included a small reference to it on the README file.

Of course, I was overlooking the actual "Level 2" definition. Besides, I think the `top_n` aggregate idea is great since it's useful and demands less work/fewer memory allocations for the result. I may be splitting hairs but it's never a bad idea to keep an eye on performance.

I also noticed issue #7 and will probably comment or try to contribute in any way possible.

Regarding my project, right now I'm getting to know the API and the environment in general by working on a trader bot to get my feet wet first. I'm considering calculating moving averages next or some other data, we'll see if something interesting comes out of it. I've had some satoshis laying around for a while with this in mind. Of course the recent craze has sparked the interest of some friends and acquaintances, whose ideas may be worth pursuing depending on some feedback/data from a working bot.

Anyways, this repo wasn't that easy to find. If you know of any other resources/projects working on a similar line I would love hear about them as well.

Cheers!

**Comment by mikerodrigues** [comment]
Awesome, it's looking a lot better. Willing to make a few more minor changes?

1. Default should probably be `Float::INFINITY` instead of 50 to. It's really easy to add a number argument, but I had to do some digging to find `Float::INFINITY`.
2. `aggregate[bid[:price]] = aggregate_base if aggregate[bid[:price]].nil?` could be a little more "Ruby" by using short-circuit:
`aggregate[bid[:price]] ||= aggregate_base`
3. `sort { |x,y| y <=> x }` can be replaced with `sort.reverse`


Sounds like a fun project. Are you using the Candles capability within RTCBX? It'll let you store historical data as 1-minute 'candles' you can push out to a database and use for calculating moving averages. I've got some code around somewhere (not on GH yet) that automates scraping historical candles from the API and creating them in "realtime" from the websocket. It throws everything into the same mysql table so you have historical data that's constantly getting the new data from the websocket.

I'm not sure of any other similar projects. I don't actively promote any of my repos. I do push them to RubyGems but I don't know how many people are actually using it.

Thanks again for your contributions.

**Comment by fdocr** [comment]
Not a problem, I just pushed the update:

1. There was an issue when using `Float::INFINITY` as a parameter to `first`, it threw `RangeError: float Inf out of range of integer`. However, I managed to do a small trick to default aggregation of the full set maintaining `nil` as the default.
2. I barely have a little over a year of working with Ruby, still seem to forget some very useful operators are out there. Thanks for the reminder! Also used it to fix the previous comment  :)
3. I had that one in mind, my train of thought went down the line of avoiding a sort and then having to reverse (since the bulkier syntax would sort in a reverse order at once). But I understand that readability is also important, specially when that line is already chaining a few methods.

And yes, I have been playing with the Candles for a bit. Some hacking on spare time this weekend may get me somewhere with them. The historical data sounds really interesting, plenty of ideas come to mind and I'll be sure to throw any suggestion to the project your way once I have some more hands on work with it.

**Comment by mikerodrigues** [comment]
Looks awesome! Thanks man. Sorry for the delay on getting this merged.

Do let me know if you think of anything else.

**Pull request merged**
